openapi: 3.0.0
info:
  {
    title: Onread API,
    version: 1.0.0,
    contact:
      { email: himanshukhaitan108@gmail.com, name: "OnRead API Support" },
  }
servers:
  - url: https:localhost:3000
paths:
  /api/books/all:
    get:
      summary: Get all Books
      operationId: FetchingAllBooks
      tags:
        - books
        - all
      responses:
        "200":
          description: Fetched
          content:
            application/json:
              schema:
                properties:
                  engagements:
                    items:
                      properties:
                        books: { description: Array of Books, nullable: true }
                    type: array

    post:
      summary: Adding a New Book
      operationId: AddingBook
      tags:
        - books
      parameters:
        - name: title
          in: query
          description: Title of the Book
          required: true
          schema: { maxLength: 50, minLength: 2, type: string }
        - name: genre
          in: query
          description: Category of the Book
          required: true
          schema: { maxLength: 50, minLength: 2, type: string }
        - name: author
          in: query
          description: Author of the Book
          required: true
          schema: { maxLength: 50, minLength: 2, type: string }
      responses:
        "200":
          description: Created
          content:
            application/json:
              schema:
                properties:
                  title:
                    {
                      description: Title of the Book,
                      minLength: 2,
                      maxLength: 50,
                      nullable: false,
                      type: string,
                    }
                  book_id:
                    {
                      description: Title of the Book,
                      minLength: 2,
                      maxLength: 50,
                      nullable: false,
                      type: string,
                    }
                  author:
                    {
                      description: Author of the Book,
                      minLength: 2,
                      maxLength: 50,
                      nullable: false,
                      type: string,
                    }
                  genre:
                    {
                      description: Genre of the Book,
                      minLength: 2,
                      maxLength: 50,
                      nullable: false,
                      type: string,
                    }
                  issuedBy:
                    {
                      description: Book Issued by,
                      nullable: false,
                      type: string,
                    }
                  updatedAt:
                    {
                      description: Date Updated At,
                      nullable: false,
                      type: string,
                    }
                  createdAt:
                    {
                      description: Date Created At,
                      nullable: false,
                      type: string,
                    }
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                properties:
                  error: { type: string, description: Error Message }
        "400":
          description: Invalid Data
          content:
            application/json:
              schema:
                properties:
                  errors: { description: List of Errors occured, type: object }
